export { default as Heading } from './Heading'
export { default as Input } from './Input'
export { default as Link } from './Link'
export { default as Text } from './Text'
export { default as View } from './View'
